# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "http://www.reduxfinance.com/"
languageCode = "en-AU"
title = "Redux Credit Finance Pvt Ltd"
publishDir = "docs"

# Metadata
[params]
  author = "Sandeep Srinivasa"
  description = "Lending to people in India without a credit bureau score"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "Redux Credit Finance Pvt Ltd + RedCarpetUp.com "
  description = "Transforming Credit In India"

# Navigation section
[params.nav]
  mission = "Our Mission"
  #services = "Services"
  team = "The Team"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "strategy"
    title = "Strategy"
    subtitle = "Transforming credit in India"
    description = "\
    <p>RedCarpetUp is also one of the innovative #MakeInIndia startups featured at GES 2017 by Department of Industrial Policy & Promotion and Niti Aayog and featured for Prime Minister Modi and Ivanka Trump on 28'th-29th Nov, 2017. We are proud that our hard work in the service of the nation is recognized by the Cabinet .</p> \
    <ul class='checked'><li><a href='https://twitter.com/DIPPGOI/status/938345126526459905/photo/1'>Compliment for RedCarpet by the Govt of India</a></li><li></li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  
# Services section
[params.services]
  enable = true
  video = false
  vidlink = "https://youtu.be/xoZsNN9UGlQ?t=299"
  title = "Our Difference"
  description = "Cutting edge data science combined with risk analysis"

  [[params.services.item]]
    icon = "icon-screen-smartphone"
    title = "Mobile first"
    description = "We use the power of the smartphone to deliver accessible financial services"

  [[params.services.item]]
    icon = "icon-eye"
    title = "Risk analysis"
    description = "Using big data analysis technology to understand risk and fraud"

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Quick servicing and disbursal"
    description = "Our proprietary loan management and accounting systems ensure industry beating disbursal and servicing time."

# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "#MakeInIndia"
    subtitle = "Make in India. Make for India"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Data Science"
    subtitle = "Cutting edge data science"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Operational Efficiency"
    subtitle = "Quick Operations"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Smartphone first"
    subtitle = "Leveraging the power of the smartphone"
    img = "images/img_2.jpg"


# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = "The team has a combined two decades experience in payments, risk, analytics and finance"

  [[params.team.item]]
    name = "Sandeep Srinivasa"
    position = "Chief Technology Officer"
    description = "Two decades of experience building payment systems for India and the United States"
    img = "images/sandeep.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Kartik Venkataraman"
    position = "Chief Executive Officer"
    description = "Two decades of experience in deep analytics and data science"
    img = "images/kartik.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "Swagat Sarma"
    position = "Head of Risk and Policy"
    description = "Almost a decade of experience managing risk and NPA at Experian"
    img = "images/swagat.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Visit our brand website - www.redcarpetup.com or send an email at support@reduxfinance.com"

  
